name: deployment
description: create a deployment

inputs:
  environment:
    description: environment name
    required: false
  environment-suffix:
    description: suffix of environment name
    required: false
  description:
    description: description of environment
    required: false
  task:
    description: task name of environment
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  url:
    description: url of deployment
  id:
    description: id of deployment
  node-id:
    description: node id of deployment

runs:
  using: 'node16'
  main: 'dist/index.js'
